export const XP_REWARDS = {
  LESSON_COMPLETE: 30,
  CHALLENGE_FIRST_TRY: 50,
  CHALLENGE_COMPLETE: 20,
  REVIEW_PERFECT: 15,
  REVIEW_GOOD: 10,
  REVIEW_OK: 5,
  STREAK_BONUS: 10,
  MODULE_COMPLETE: 100,
  BOSS_BATTLE_WIN: 150,
} as const

export type XPRewardKey = keyof typeof XP_REWARDS
